export default {
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  PRIMARY_COLOR: '#8707EC',
  SECONDARY_COLOR: '#14FC7D',
  FONT_WEIGHT_LIGHT: 200,
  FONT_WEIGHT_MEDIUM: 600,
  FONT_WEIGHT_HEAVY: 800,
  TEXT_LIGHT: '#FFF',
  TEXT_DARK: '#000',
};
